hybrid_a_star:
    xy_grid_resolution_m:  2    # [m]
    yaw_grid_resolution_deg:  15.0  # [deg]
    path_interpolate_resolution_m:  0.1  # [m] path interpolate resolution
    number_of_steer_command:  20  # number of steer command
    switch_back_penalty_cost:  100.0  # switch back penalty cost
    backward_penalty_cost:  5.0  # backward penalty cost
    steer_angle_change_penalty_cost:  5.0  # steer angle change penalty cost
    steer_change_penalty_cost:  1.0         # steer change penalty cost
    heuristic_cost:  5.0  # Heuristic cost

vehicle_model:
    wheel_base_m: 3.0  # rear to front wheel
    width_m: 2.0  # width of car
    distance_from_rear_tire_to_front_bumper_m: 3.3  # distance from rear to vehicle front end
    distance_from_rear_tire_to_rear_bumper_m: 1.0  # distance from rear to vehicle back end
    maximum_steering_angle_deg: 34.4  # 0.6[rad] maximum steering angle

stanley_controller:
    steer_control_gain: 0.5  # control gain
    speed_proportional_gain: 1.0  # speed proportional gain
    delta_time_s: 0.1  # [s] time difference
    wheel_base_m: 2.9  # [m] Wheel base of vehicle
    maximum_steering_angle_deg: 30.0  # [rad] max steering angle    